import type {
  PersonaAssessment,
  PersonaReview,
  DecisionReport,
  LabelMapping,
  AggregateRanking,
} from '../types';
import { PERSONAS } from '../config/personas';
import { deAnonymize, extractVerdict } from '../utils/formatting';

export interface MarkdownReportData {
  startupIdea: string;
  stage1Results: PersonaAssessment[];
  stage2Results: PersonaReview[];
  stage3Result: DecisionReport;
  labelMapping: LabelMapping;
  aggregateRankings: AggregateRanking[];
  selectedModel: string;
}

export function buildReportMarkdown(data: MarkdownReportData): string {
  const verdict = extractVerdict(data.stage3Result.response);
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const lines: string[] = [];

  // Header
  lines.push('# Startup Council — Evaluation Report');
  lines.push('');
  lines.push(`**Date:** ${dateStr}  `);
  lines.push(`**Model:** ${data.selectedModel}  `);
  if (verdict) {
    lines.push(`**Verdict:** ${verdict}`);
  }
  lines.push('');
  lines.push(`> **Startup Idea:** ${data.startupIdea}`);
  lines.push('');

  // Stage 1
  lines.push('---');
  lines.push('');
  lines.push('## Stage 1: Individual Assessments');
  lines.push('');

  for (const result of data.stage1Results) {
    const persona = PERSONAS[result.personaId];
    lines.push(`### ${persona.emoji} ${persona.name} — ${persona.title}`);
    lines.push('');
    lines.push(result.response.trim());
    lines.push('');
  }

  // Stage 2
  lines.push('---');
  lines.push('');
  lines.push('## Stage 2: Cross-Review & Ranking');
  lines.push('');

  for (const result of data.stage2Results) {
    const persona = PERSONAS[result.personaId];
    const deAnonymizedReview = deAnonymize(result.review, data.labelMapping);
    lines.push(`### ${persona.emoji} ${persona.name} — ${persona.title}`);
    lines.push('');
    lines.push(deAnonymizedReview.trim());
    lines.push('');
  }

  // Rankings table
  if (data.aggregateRankings.length > 0) {
    lines.push('### Aggregate Rankings');
    lines.push('');
    lines.push('| Rank | Advisor | Avg. Rank |');
    lines.push('|------|---------|-----------|');
    for (let i = 0; i < data.aggregateRankings.length; i++) {
      const r = data.aggregateRankings[i];
      const persona = PERSONAS[r.personaId];
      lines.push(`| #${i + 1} | ${persona.emoji} ${persona.name} | ${r.averageRank.toFixed(1)} |`);
    }
    lines.push('');
  }

  // Stage 3
  lines.push('---');
  lines.push('');
  lines.push('## Stage 3: Final Decision');
  lines.push('');
  if (verdict) {
    lines.push(`**Verdict: ${verdict}**`);
    lines.push('');
  }
  lines.push(data.stage3Result.response.trim());
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by Startup Council · ${dateStr}*`);
  lines.push('');

  return lines.join('\n');
}

export function exportCouncilMarkdown(data: MarkdownReportData): void {
  const markdown = buildReportMarkdown(data);

  // Create a Blob and trigger download
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const ideaSlug = data.startupIdea
    .slice(0, 40)
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
  const dateStr = new Date().toISOString().slice(0, 10);

  const a = document.createElement('a');
  a.href = url;
  a.download = `startup-council-${ideaSlug}-${dateStr}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
